import { Schema, model } from 'mongoose';

const FormFieldSchema = new Schema({
  key: { type: String, required: true },       // internal key
  label: { type: String, required: true },     // question asked to user

  type: {
    type: String,
    enum: ['string', 'number', 'date'], 
    default: 'string'
  },

  // optional constraints for number fields
  minLength: Number,
  maxLength: Number,

  required: { type: Boolean, default: true }
});

const AgentSchema = new Schema({
    adminId: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    agentName: {
        type: String,
        required: true
    },
    agentType: {
        type: String,
        enum: ['query', 'survey', 'form'],
        default: 'query', // Sets a default so existing agents don't break
        required: true
    },
    language: {
        type: String,
        default: 'en' // Default to English
    },
    knowledgeBase: {
        type: String, // cloudinary url
    },
    knowledgeBasePublicId: {
        type: String, // cloudinary public id
    },
    // ONLY for form agents
    formFields: [FormFieldSchema],
    // These are generated by AI based on the knowledgeBase
    systemPrompt: {
        type: String
    },
    greeting: {
        type: String
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

export default model('Agent', AgentSchema);